plugins {
    id 'java-library'
    id("com.github.spotbugs") version "6.1.11"
    id 'com.github.davidmc24.gradle.plugin.avro' version '1.9.1'
}

group = 'ru.katacademy.bank-app'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://packages.confluent.io/maven/' }
}

dependencies {
    api platform(project(":bank-bom"))

    annotationProcessor platform(project(":bank-bom"))
    compileOnly platform(project(":bank-bom"))
    testAnnotationProcessor platform(project(":bank-bom"))

    api 'com.fasterxml.jackson.core:jackson-databind'
    api 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
    api 'jakarta.validation:jakarta.validation-api'
    api 'org.slf4j:slf4j-api'
    api 'org.apache.avro:avro:1.11.3'
    api 'io.confluent:kafka-avro-serializer:7.7.1'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    compileOnly 'com.github.spotbugs:spotbugs-annotations'
    compileOnly 'org.aspectj:aspectjrt'

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.mockito:mockito-junit-jupiter'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

test {
    useJUnitPlatform()
}

tasks.spotbugsMain {
    reports.create("html") {
        required = true
        outputLocation = file("$rootDir/reports/spotbugs-bank-shared.html")
        stylesheet = 'fancy-hist.xsl'
    }
    excludeFilter = file("config/spotbugs/exclude-filter.xml")
}

check {
    dependsOn tasks.spotbugsMain, tasks.spotbugsTest
}

jar {
    enabled = true
    archiveClassifier = ''
}

sourceSets {
    main {
        java {
            srcDirs += "${buildDir}/generated-main-avro-java"
        }
    }
}

avro {
    stringType = "String"
    fieldVisibility = "PRIVATE"
}

tasks.withType(JavaCompile) {
    dependsOn tasks.generateAvroJava
}